var commentsArray = [

    {
       "id": 1,
       "parent": null,
       "created": "2021-09-18",
       "modified": "2021-09-18",
       "title": "Works like magic",
         "content": "I bought this to help with my knee recovery. It helped greatly which makes this well worth it. However, I've noticed increased flexibility in my back since taking this, which is a nice - albeit unexpected - result.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Elle",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 2,
       "parent": null,
       "created": "2021-09-01",
       "modified": "2021-10-01",
       "title": "Highly recommended product. Thanks.",
    "content": "Good product this is my 5 order will order 1 to 2 per month. Highly recommended. Can use use safely. Will keep on ordering.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Niamh G",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 3,
       "parent": null,
       "created": "2021-08-10",
       "modified": "2021-09-21",
       "title": "I really like the taste",
       "content": "I have been using collagen for about a year now. It has made a tremendous difference in the strength of my finger nails. This is the third brand I have tried and I can say that this particular brand also has a very great taste to it. ",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Elsie Chapman",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 4,
       "parent": null,
       "created": "2021-07-19",
       "modified": "2021-08-19",
       "title": "Great price!!",
      "content": "Exactly what was expected. No change to the flavor of my shakes",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Kimberely",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 5,
       "parent": null,
       "created": "2021-07-07",
       "modified": "2021-10-16",
       "title": "So far so good...",
    "content": "So far so good. I haven’t used it long enough to report any results (only had it a few days) but did want to say it completely dissolved in my coffee and I haven’t noticed any taste. Getting something that I would be able to drink and not be gross me out was first priority.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Gemma",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 4,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 6,
       "parent": null,
       "created": "2021-06-21",
       "modified": "2021-10-09",
       "title": "Hair skin nails joints stomach everything",
    "content": "The value for your money is great. This product makes my hair very soft and has thickened it. Also the benefits to your skin are great and have kept me using it. Normally in winter my hands crack and bleed and they have not done so since using. Also the pain in my joints has eased very much. And probably the best benefit is that it has gotten rid of the toenail fungus which I had fought for years and tried several products to try to get rid of. It is now completely gone. Do not give up hope because it took about 10 months to completely get rid of. I will never give up this product.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Marie Luna",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 12,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 8,
       "parent": null,
       "created": "2021-06-05",
       "modified": "2021-09-28",
       "title": "Great product!",
    "content": "I have been using this product for about 6 months now. I can honestly say that I notice a difference in my joints. I am less achy and my digestion is better. As a huge bonus my hair has never looked better and my nails are strong. I also have noticed my skin looks better as well, I would say youthful. I mix it in my morning coffee and it dissolves well and has no flavor. The price is great as well. I will continue to keep this collagen in my daily routine since it makes a huge difference for me. I recommend this product.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Glori. B",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 9,
       "parent": null,
       "created": "2021-05-14",
       "modified": "2021-09-17",
       "title": "Knee continually improving",
      "content": "I’ve been using this exact collagen for over a year now. I had a knee that was bothering me and couldn’t believe how badly it was slowing me down at 40. (I fell on it really hard playing sports as a child and it’s never been right since.) The snap/crackle/pop sound effects just walking up stairs were ridiculous. I started using this and before I’d finished the first container, I could feel an improvement. I had a hunch that over time, it would continue to get better as the collagen rebuilt the cartilage at my knee, and indeed it did. Fast forward many months and I’ve returned to working out again with zero pain or noises and although not as important, my hair, skin, and nails look phenomenal. I put one scoop per day into my bulletproof coffee and then give it a blitz in my personal blender. I’ve never noticed any flavor at all and thanks to the blender, I’ve never had any clumps either. Good stuff. Highly recommend.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Mrs. Peters",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 8,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 10,
       "parent": null,
       "created": "2021-05-02",
       "modified": "2021-08-17",
       "title": "Very nice Collagen",
    "content": "I’ve been trying different brand & types of Collagen for over a year now. After trying this brand I’ll surely buy again. It comes in at a good price. The scoop provided was my daily guide for how much to use. Typically it’s 1 scoop a day. I mix it in with my daily morning yogurt and don’t taste any difference which is great. I see better digestion, hair growth & thickness, nail growth & hardness & a better skin complexion. Collagen is so important for our bodies. This brand is one I’ll turn to due to the quality & value of the product. Subscribe & save is also offered so there can be additional savings with the convenience of ordering when needed. Based on my experience I do recommend.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Casey",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 11,
       "parent": null,
       "created": "2021-04-05",
       "modified": "2021-08-24",
       "title": "My search has ended",
      "content": "I've tried other multi collagens but this the one for me..it's very fine when I mix on my morning coffee with no added taste.I started looking for a replacement when my regular went up in price. I should add my skin is so soft and I have to cut my nails more often..glad I do them myself..long and strong. I believe my search is over unless they raise their price, which I believe can't be beat..along with quality!",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Natalia J.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 12,
       "parent": null,
       "created": "2021-03-21",
       "modified": "2021-06-13",
       "title": "I think it’s time to cut them",
    "content": "I’ve been using this product for about 6 months, my hair is really grown and my nails are crazy long, I think it’s time to cut them off, I will continue to get this, I love the results! You will too!<br>I file my nails 💅 I don’t cut them, filing them seems to work best, I hope y’all have the same results as I have.🥰❤️🥰",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Alesha",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 13,
       "parent": null,
       "created": "2021-03-03",
       "modified": "2021-06-01",
       "title": "Glad I Ordered!",
    "content": "I will reorder this product. I am pleased that it’s tasteless and mixes smoothly into anything. I most often put a scoop in a jar of warm water and drink it down. There really is no smell and taste, I have had others that I sent back right away or tossed out because of the horrific taste. It’s free of all the products I am allergic to, fortunately! I will reorder this product!",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Stacey Burton",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 14,
       "parent": null,
       "created": "2021-02-24",
       "modified": "2021-05-26",
       "title": "So far, so good!",
    "content": "This is my first time trying this specific brand. It doesn’t have a taste to it. It’s easy to dissolve in my coffee in the mornings. I’ll say it’s a pretty nice brand for the price. My joints are no longer hurting and my skin is so soft and subtle. My hyperpigmentation is fading some as well too.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Laura",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 15,
       "parent": null,
       "created": "2021-01-17",
       "modified": "2021-05-04",
       "title": "Love this collagen! Definitely buying more!",
    "content": "Awesome product! Love this collagen! All collagens are not created equal! While many do not dissolve well in hot beverages and rarely dissolve well in both! This collagen has no taste and dissolves well in both hot and cold beverages. Love it! I not only purchased for myself but I bought a few for my sister and friends. They all love it. We all have it with our sugar free hot chocolate. Delicious!",
       "attachments": [],
       "pings": [],
         "page": 3,
       "creator": 1,
       "fullname": "Holly. J",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 12,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 16,
       "parent": null,
       "created": "2020-11-27",
       "modified": "2020-04-21",
       "title": "Too early to tell",
    "content": "It’s still early days, so I can't give any information on it just yet. I did use it in my coffee though and it did not clump and it was flavorless so that is good.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Sabrina Owens",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 17,
       "parent": null,
       "created": "2020-10-02",
       "modified": "2021-03-20",
       "title": "this stuff is amaaazing",
    "content": "This stuff iNCREDIBLE!!!! I made my first drink with 2 scoops, put it in a sealed container. Shook the heck out of it and omg, I have so much energy! It doesn't taste bad and if u shake the heck out of it itbis not clumpy. HIGHHHHHHHLYYYY RECOMMEND!!!!",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Aisha Harris",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 18,
       "parent": null,
       "created": "2020-09-13",
       "modified": "2021-01-24",
       "title": "Helps with joint pain.",
    "content": "Has been a big time pain relief. I mix a scoop with 1/2 cup of mocha latte and gulp it down. Big difference after a few days, now i skip a day here and there.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Katherine G",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 19,
       "parent": null,
       "created": "2020-09-04",
       "modified": "2020-12-29",
       "title": "Great collegen",
    "content": "I purchased this particular collagen because it has all three stages. There’s no weird flavor and this mixes well.<br>The purpose of taking collagen does help with physical attributes such as inflammation small aches and pains and I have noticed that my finger nails have grown pretty well.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Christina Page",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 20,
       "parent": null,
       "created": "2020-08-10",
       "modified": "2020-11-17",
       "title": "great for joint pain relief!",
    "content": "i originally started using collagen for joint pain relief. absolutely have noticed a huge difference. i have arthritis mainly in my knee so it was getting difficult to move. this makes it possible to get up and walk/run/exercise/whatever i want to do without taking a bunch of meds everyday. this is the 3rd brand i’ve tried and i think it dissolves better than the other brands on the market. i’ve purchased this 2 times in a row and will likely continue to purchase this brand.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Amanda",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 21,
       "parent": null,
       "created": "2020-07-26",
       "modified": "2020-10-12",
       "title": "Amazing health benefits",
    "content": "I bought this for the health benefits. Wanted clearer skin and to strengthen my nails and to decrease my knee pain.<br>I will be buying my second container soon and happy so far with my results.",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Leah S",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 22,
       "parent": null,
       "created": "2020-07-14",
       "modified": "2020-08-08",
       "title": "Love this stuff",
    "content": "I have bought multiple containers of this. It works - my nails grow SO fast when I use it, even though I buy it more for nutritional purposes. It does blend in both cold and hot beverages. I mix it with teas (hot and cold), chai, and apple cider and the flavor is non-existent.",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Lena",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 23,
       "parent": null,
       "created": "2020-06-28",
       "modified": "2020-07-25",
       "title": "Helps",
       "content": "It’s tasteless, dissolves completely and has helped my knees. My knees had started slipping out of joint about every time I got down on my knees. Now it only happens occasionally. I’m a gardener and often need to get down on my knees.",
        "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Amirah Clark",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 24,
       "parent": null,
       "created": "2020-05-19",
       "modified": "2020-05-17",
       "title": "Works very well.",
    "content": "I keep coming back to this collagen. I noticed a difference on my skin within a week of taking this. I have stirred it into tea, soup, iced lattes (I mix it into the espresso shots first) and other things, with no to very little taste. It also blends well into cold drinks if you use a blender. This is an amazing product at a price that won't break your bank. As someone who's been using collagen products for at 3 to 4 years now, and have spent way more for products that had way fewer (or no) results I can't recommend this enough.",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Paige",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 25,
       "parent": null,
       "created": "2020-03-20",
       "modified": "2020-03-09",
       "title": "Good product",
    "content": "I bought this product to support my daily exercise regiment, and am happy with my purchase. Some of these powders can be too sweet or upset my stomach, but this one has no taste and is gentle. I also like that it has a full range of collagen types, will buy again.",
    "attachments": [],
       "pings": [],
      "page": 5,
       "creator": 1,
       "fullname": "Stephanie W.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 16,
       "user_has_upvoted": false,
       "is_new": false
    },
    
  
    
    ]
    
    var usersArray = [
       {
          id: 1,
          fullname: "Current User",
          email: "current.user@viima.com",
          profile_picture_url: "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png"
       }
      
    ]
    