var commentsArray = [

    {
       "id": 1,
       "parent": null,
       "created": "2021-11-12",
       "modified": "2021-09-18",
       "title": "Potent digestive aid",
         "content": "Who'd have known this little bottle's content would clean your gut and quite a clean out indeed."+

         "<br><br>If you have never tried digestive aids before, I recommend not taking more than 2 daily. Otherwise, you might as well sleep on your toilet bowl."+
         
       "<br><br>The pills are so potent I am amazed by my more-than-regular bowel movement. The funny thing is, with these kind of digestive aids stuff, it'd normally dry you out and make you lethargic. Queen Cleanse doesn't seem to give that or any negative side effects. The only thing it does is definitely the cleansing, be cautious to consume this on the days you aren't close to any toilet."+
         
        "<br><br>Other than that, a great product as long as used & consumed responsibly.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Megan",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 14,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 2,
       "parent": null,
       "created": "2021-11-03",
       "modified": "2021-10-01",
       "title": "Queen Cleanse",
    "content": "The day I received Queen Cleanse, was the day I started. Approx 20 hrs later things started to happen. All I can say is make sure you're close to the bathroom! As there ain't no warning 🤣. Plus dont take them in the morning if you're planning on heading out! Lol 6 days in, I'm 2kg down and I have been a bit more active, I usually have an afternoon nap, but i havent since the 2nd day of taken the pills.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Georgia",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 3,
       "parent": null,
       "created": "2021-10-27",
       "modified": "2021-09-21",
       "title": "Lives up to expectations",
       "content": "At first I was skeptical about this product. I have tried a number of supplements to assist with GI issues. As a celiac I am also careful about ingredients. 2 weeks later and I am still very happy with this product. My Gut is much more comfortable and inflammation has reduced significantly. Very happy customer",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Kelly Grey",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 4,
       "parent": null,
       "created": "2021-10-20",
       "modified": "2021-08-19",
       "title": "The best product I have ever used.",
      "content": "This product is a game changer! For the first time in years my digestive issues are gone. The bloat, the constipation and the overuse of laxatives have left me miserable. When I say I have tried everything I have. I literally just went to the doctor and they asked me how things were moving along since it's been a 11 year battle. I showed them the bottle and my doctor took a picture of it. I told them now I go 1 to 2 times a day, no cramping. It's literally changed my life."+

      "<br><br>It's a small capsule, easy to swallow, no bad taste or after effects.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Heidi S",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 5,
       "parent": null,
       "created": "2021-10-08",
       "modified": "2021-10-16",
       "title": "Absalutly fantastic...it works",
    "content": "Super easy to take.if you miss a night it takes me 24 hrs for it to kick in again.weight loss happens pretty fast and yes i do have a waist again.didnt weigh myself but have lost alot of weight from my back....yes of all places stomach tops of my legs...i love this product would give 10 stars if i could",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Lara",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 6,
       "parent": null,
       "created": "2021-09-30",
       "modified": "2021-10-09",
       "title": "Absolutely Works",
    "content": "This stuff really works. After day two, you will poop out stuff you ate years ago. I suffer from IBS and have since taken these pills. My symptoms have reduced, and I have less bloating and a lot more energy.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Rachel Zaynab",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 7,
       "parent": null,
       "created": "2021-09-12",
       "modified": "2021-09-28",
       "title": "Amazing Product",
    "content": "After receiving Queen Cleanse, I was eager to try it out and it worked like magic! It was like I had no bloating at all. Also I lost some weight after using it for 30 days. Will buy again for sure",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Becca H.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 9,
       "parent": null,
       "created": "2021-08-19",
       "modified": "2021-09-17",
       "title": "This really works",
      "content": "This product really works. There is no pain associated like with other laxatives. Will be buying again!",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Tiffany",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 10,
       "parent": null,
       "created": "2021-08-06",
       "modified": "2021-08-17",
       "title": "Really does work!!",
        "content": "Love my Queen Cleanse really does work. Helped with bloating and digestion after first use.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Erica Hall ",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 11,
       "parent": null,
       "created": "2021-07-21",
       "modified": "2021-08-24",
       "title": "It works!!!",
      "content": "I’m planning for an upcoming wedding & this has worked better to cleanse than anything I’ve used before. Will definitely re purchase! Thankyou!!",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Katie Ross",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 4,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 12,
       "parent": null,
       "created": "2021-07-17",
       "modified": "2021-06-13",
       "title": "AwesOMe",
    "content": "Great product. Cleanses as well as gets rid of large intestine bloating straight away. Thank you 🙏🕉",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Daisy",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 13,
       "parent": null,
       "created": "2021-07-03",
       "modified": "2021-06-01",
       "title": "Great product!",
    "content": "Ordered this product due to digestive issues and I can start to feel a noticeable change!",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Veronica",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 14,
       "parent": null,
       "created": "2021-06-27",
       "modified": "2021-05-26",
       "title": "Awesome product that works!!!",
    "content": "KaiserFit has amazing products that work, I have used this product previously and highly recommend it.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Michelle",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 15,
       "parent": null,
       "created": "2021-06-06",
       "modified": "2021-05-04",
       "title": "Great product",
    "content": "This product has cleaned me out. I feel lighter and more alert after having this product within the first week.",
       "attachments": [],
       "pings": [],
         "page": 3,
       "creator": 1,
       "fullname": "Rita Greene",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 16,
       "parent": null,
       "created": "2021-06-02",
       "modified": "2020-04-21",
       "title": "Great Product",
    "content": "Could see the difference within a few days, less bloating and trimmer. highly recommend",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Cory Hanson",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 17,
       "parent": null,
       "created": "2021-05-28",
       "modified": "2021-03-20",
       "title": "Great product!! Recommend",
    "content": "Product does exactly what it’s suppose to, stoked with results",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Lana G",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 18,
       "parent": null,
       "created": "2021-05-23",
       "modified": "2021-01-24",
       "title": "Great product",
    "content": "I feel so much better and it wasn’t harsh on the stomach like laxatives are",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Claudia",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 19,
       "parent": null,
       "created": "2021-05-11",
       "modified": "2020-12-29",
       "title": "Good product",
    "content": "Working well so far, if this keeps up I will definitely buy again",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Vanesa",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 20,
       "parent": null,
       "created": "2021-04-14",
       "modified": "2020-11-17",
       "title": "Very effective",
    "content": "This product makes me feel so much more energetic and my body feels less bloated and the waist trimming complex actually does its job over time!",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Anita A.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 21,
       "parent": null,
       "created": "2021-04-01",
       "modified": "2020-10-12",
       "title": "Will get it again!",
    "content": "This product is really good. I usually took 2 tablets after dinner at 8pm and everything is cleared out in the morning. Sometimes I had urged in the afternoon as well. I feel light whenever my bowel is moved.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Eliza Mcdonald",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 22,
       "parent": null,
       "created": "2021-03-19",
       "modified": "2020-08-08",
       "title": "Very effective",
        "content": "Good product. Effective.",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "MJ",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 23,
       "parent": null,
       "created": "2021-01-16",
       "modified": "2020-07-25",
       "title": "Amazing!!",
       "content": "This stuff is all what it is cracked up to be! I had stuff from my childhood come out after a few days of this product lol. Worth the price.",
        "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Darcie. W",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 24,
       "parent": null,
       "created": "2020-11-22",
       "modified": "2020-05-17",
       "title": "Feel way better",
    "content": "Been feeling way better. Made me regular and don’t feel sluggish anymore. Will be buying more of this. Highly recommend it. I’m not sure if I lost anything as I don’t keep track of that. But my energy levels are up."+

    "<br><br>Good value for the money. Now that I’ve been taking it for a while I’m actually going to the bathroom 2-3 times a day. Before I was lucky to go every other day. ",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Tanisha",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 9,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 25,
       "parent": null,
       "created": "2020-09-13",
       "modified": "2020-03-09",
       "title": "This is great!",
    "content": "This stuff is a miracle! To be honest, I wasn’t expecting too much before ordering this supplement. No matter what I do, I still have a belly pouch that really annoys me. I found this supplement on some web ad, and I thought I would try it. First day I was upset because I experienced nothing. But on day two! Wow! Great bathroom trips, and I felt just more clean. Then I started seeing the belly pouch being smaller and having a much smaller waistline. I couldn’t believe it! I am definitely going to order more of this.",
    "attachments": [],
       "pings": [],
      "page": 5,
       "creator": 1,
       "fullname": "Faith",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },

    {
        "id": 26,
        "parent": null,
        "created": "2020-08-23",
        "modified": "2020-03-09",
        "title": "This stuff does wonders!",
     "content": "Wow. This stuff is amazing! Normally when you buy “cleansing” products they have a tendency to make you have to RUN to the bathroom, but this is not like that at all. It definitely helps keep things regular without the emergency urge or stomach cramping. But the main reason why I love this product is that it helps with bloating! Normally around that time of the month I get HORRIBLE bloating. Like, I breathe in air and take a sip of water and suddenly blow up like a balloon. But since taking this product for a couple of weeks, I didn’t experience any weight gain or bloating during my cycle. Please never discontinue this item!",
     "attachments": [],
        "pings": [],
       "page": 5,
        "creator": 1,
        "fullname": "Lucie Floyd",
        "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
        "created_by_admin": false,
        "created_by_current_user": false,
        "upvote_count": 0,
        "user_has_upvoted": false,
        "is_new": false
     },

     {
        "id": 27,
        "parent": null,
        "created": "2020-05-19",
        "modified": "2020-03-09",
        "title": "I was skeptical but not anymore",
     "content": "I was told by a nutritionist that I needed to improve my good bacteria in the stomach and after trying a couple of alternatives to this one I decided to stick with this one. I had 'stuff' in my intestine that probably was camping there for longer than I thought it was possible. Kaiser Greens shoe them away and kindly (for me). Valuable product.",
     "attachments": [],
        "pings": [],
       "page": 5,
        "creator": 1,
        "fullname": "Elsie Warren",
        "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
        "created_by_admin": false,
        "created_by_current_user": false,
        "upvote_count": 1,
        "user_has_upvoted": false,
        "is_new": false
     },

     {
        "id": 28,
        "parent": null,
        "created": "2020-05-02",
        "modified": "2020-03-09",
        "title": "My brain fog is gone.",
     "content": "I'm trying to eat healthier, so I thought I would try this for starters. Within a few days my brain fog has vanished. I'm no longer content sitting on the couch in front of the TV. I feel like I need to be doing something now. Where I didn't want to do @#$& before. I can't even stand watching tv now. Winter is here. WTH am I supposed to do with my time? Lol. I've started painting the rooms in my house.<br><br> This is no lie, and no joke. I read similar reviews. Don't take my word for it. Read a few yourself.",
     "attachments": [],
        "pings": [],
       "page": 5,
        "creator": 1,
        "fullname": "Chelsea",
        "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
        "created_by_admin": false,
        "created_by_current_user": false,
        "upvote_count": 4,
        "user_has_upvoted": false,
        "is_new": false
     },
    
  
    
    ]
    
    var usersArray = [
       {
          id: 1,
          fullname: "Current User",
          email: "current.user@viima.com",
          profile_picture_url: "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png"
       }
      
    ]
    