var commentsArray = [

    {
       "id": 1,
       "parent": null,
       "created": "2021-10-16",
       "modified": "2021-10-16",
       "title": "𝗔𝗺𝗮𝘇𝗶𝗻𝗴 𝗽𝗿𝗼𝗱𝘂𝗰𝘁. 𝗜 𝗰𝗮𝗻 𝗳𝗶𝗻𝗱 𝗱𝗶𝗳𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗮𝗹𝗿𝗲𝗮𝗱𝘆",
         "content": "Amazing product. I can find difference very much with intensive workout. I have experienced awesome results. Thank you",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Ida K",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 2,
       "parent": null,
       "created": "2021-10-01",
       "modified": "2021-10-01",
       "title": "𝗙𝗶𝘃𝗲 𝗦𝘁𝗮𝗿𝘀",
    "content": "EXCELLENT Service provided by KaiserFit. Product is as per description. It works.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Gracie",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 3,
       "parent": null,
       "created": "2021-09-21",
       "modified": "2021-09-21",
       "title": "𝗚𝗥𝗘𝗔𝗧 𝗦𝗟𝗘𝗘𝗣 𝗔𝗜𝗗𝗘",
       "content": "I have not slept well in years!!!!!! I have tried everything. This product is AWESOME. I take it and about 25 minutes later I start to feel drowsy. Then, an entire night's sleep. Undisturbed. And, no groggy feeling in the morning. I love it!!!!\n"+
       "\n As far as the weight loss, it does seem to help. Lost about 4 pounds in 3.5 weeks. I would highly recommend this product for sleep assistance.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Nora Lawson",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 9,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 4,
       "parent": null,
       "created": "2021-08-19",
       "modified": "2021-08-19",
       "title": "𝗙𝗮𝗻𝘁𝗮𝘀𝘁𝗶𝗰 𝘀𝗹𝗲𝗲𝗽!",
      "content": "I'm a shift worker who primarily works nights, and as such sleep has always been an issue. Quality sleep that is. I'm always on the lookout for something that is health and fitness oriented and also improves sleep quality. I was recommended this by a co-worker and after 1 bottle i think i'm sold. I feel that i can drift off to sleep easier, but the largest impact is that i sleep very deeply during my sleep cycle. As far as the purported fat loss properties are concerned, I believe I wake up looking a bit more leaner day by day but I have yet to weigh myself.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Melissa",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 11,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 5,
       "parent": null,
       "created": "2021-10-16",
       "modified": "2021-10-16",
       "title": "𝗜𝘁 𝘄𝗼𝗿𝗸𝘀",
    "content": "It works ive lost 5 pounds in the first week, and 3 pound in the second week with excersize. Also i take this 15 minutes before bed. I get in bed and get on my phone about 10 minutes of laying down you get sleepy and than doze off and when you wake up... WOW you wake up so comfortable and not groggy. its good",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Harmony",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 6,
       "parent": null,
       "created": "2021-10-09",
       "modified": "2021-10-09",
       "title": "𝗚𝗼 𝗧𝗼 𝗕𝗲𝗱 𝗔𝗻𝗱 𝗕𝘂𝗿𝗻!",
    "content": "I lost one and a half pounds my first night using it. So far so good!",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Cassie. C",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 8,
       "parent": null,
       "created": "2021-09-28",
       "modified": "2021-09-28",
       "title": "𝗧𝗵𝗶𝘀 𝗶𝘀 𝗮 𝗴𝗿𝗲𝗮𝘁 𝗽𝗿𝗼𝗱𝘂𝗰𝘁.",
    "content": "Been using it for a few days now but loving it so far",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Alina B",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 9,
       "parent": null,
       "created": "2021-09-17",
       "modified": "2021-09-17",
       "title": "𝗚𝗿𝗲𝗮𝘁 𝗽𝗿𝗼𝗱𝘂𝗰𝘁",
      "content": "Love it",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Isabelle",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 10,
       "parent": null,
       "created": "2021-08-17",
       "modified": "2021-08-17",
       "title": "𝗔𝗺𝗮𝘇𝗶𝗻𝗴 𝗽𝗿𝗼𝗱𝘂𝗰𝘁!",
    "content": "It takes time but you can tell within 3- 4 weeks of your fat loss! 10/10 recommended !!",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Victoria Barlow",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 11,
       "parent": null,
       "created": "2021-08-24",
       "modified": "2021-08-24",
       "title": "𝗜 𝗹𝗼𝘃𝗲 𝘁𝗵𝗲 𝗾𝘂𝗮𝗹𝗶𝘁𝘆 𝗼𝗳 𝘀𝗹𝗲𝗲𝗽 𝗜 𝗮𝗺 𝗴𝗲𝘁𝘁𝗶𝗻𝗴 𝘄𝗶𝘁𝗵 𝗡𝗶𝗴𝗵𝘁 𝗕𝘂𝗿𝗻",
      "content": "Ive always been a fan of KaiserFit supplements and this doesn’t disappoint. I have only been back on this a few days but my sleep is so much better! Getting quality sleep is the key to adding in weight loss when you change your diet and exercise.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Angie",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 12,
       "parent": null,
       "created": "2021-06-13",
       "modified": "2021-06-13",
       "title": "𝗪𝗼𝗿𝗸𝗲𝗱 𝘄𝗶𝘁𝗵𝗼𝘂𝘁 𝗮𝗻𝘆 𝘀𝗶𝗱𝗲 𝗲𝗳𝗳𝗲𝗰𝘁𝘀.",
    "content": "I was able to use this product at night and be unaffected which was nice due to the other bad experiences I have had with other sleep aids. So this product I would rate doing very well for the simple fact that I had no horrible side effects.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Lena P.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 4,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 13,
       "parent": null,
       "created": "2021-06-01",
       "modified": "2021-06-01",
       "title": "𝗭𝗭𝗭𝗭𝗭𝗭𝗭𝗭",
    "content": "I've always been skeptical of sleep aides, but this product does exactly what it says. I took one pill about 30 minutes before bed and felt more relaxed as I tried to fall asleep. My mind wasn't racing as usual. Then, I actually stayed asleep! I wake up every morning feeling rested and ready to take on the day. \n"+
       "\n I haven't been taking it long enough to notice any change in my weight, but I know how important sleep is to a diet, so I'm sure this product will be beneficial in the long run.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Lillian Watson",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 9,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 14,
       "parent": null,
       "created": "2021-05-26",
       "modified": "2021-05-26",
       "title": "𝗜𝘁 𝘄𝗼𝗿𝗸𝘀 𝗴𝗿𝗲𝗮𝘁 𝗳𝗼𝗿 𝗺𝗲, 𝗜 𝘀𝗹𝗲𝗲𝗽 𝗻𝗲𝗮𝗿𝗹𝘆 𝟳 𝗵𝗼𝘂𝗿𝘀 𝗽𝗲𝗿 𝗻𝗶𝗴𝗵𝘁",
    "content": "I get great sleep with one of these pills per night - I never drink caffeine past 3 pm, never no matter what. Love that it has fat burning properties in it because I am currently working on losing fat and firming up after gaining weight earlier this year.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "SALLY MICHELL",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 15,
       "parent": null,
       "created": "2021-05-04",
       "modified": "2021-05-04",
       "title": "𝗙𝗶𝗻𝗮𝗹𝗹𝘆 𝗮𝗯𝗹𝗲 𝘁𝗼 𝗰𝗮𝘁𝗰𝗵 𝘀𝗼𝗺𝗲 𝗭𝗭𝗭𝘀 𝗮𝗻𝗱 𝗯𝘂𝗿𝗻 𝗳𝗮𝘁",
    "content": "I originally started using Queen Night Burner to help with my insomnia. It was really getting in the way of my bodybuilding goals. Fast forward a few restful nights, I also lost 2 lbs during my first week of use! I love how it both helps me sleep and also lose weight at the same time.",
       "attachments": [],
       "pings": [],
         "page": 3,
       "creator": 1,
       "fullname": "Connie Coleman",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 8,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 16,
       "parent": null,
       "created": "2021-04-21",
       "modified": "2021-04-21",
       "title": "𝗬𝗲𝘁 𝗮𝗻𝗼𝘁𝗵𝗲𝗿 𝗵𝗼𝗺𝗲 𝗿𝘂𝗻 𝗳𝗿𝗼𝗺 𝗞𝗮𝗶𝘀𝗲𝗿𝗙𝗶𝘁!",
    "content": "I feel lighter but it’s still early days of using it plus I haven’t weighed myself yet though my jeans don’t feel as tight lol. What I can say is that I am sleeping without any struggle which has been a problem in the past and I'm sleeping great with no hangover.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Maisie J",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 17,
       "parent": null,
       "created": "2021-03-20",
       "modified": "2021-03-20",
       "title": "𝗟𝗼𝘃𝗲 𝗶𝘁",
    "content": "This product definitely makes you sleepy. Not sure if it’s a fat burner but I have lost about 10 pounds in three months.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Taylor",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 18,
       "parent": null,
       "created": "2021-01-24",
       "modified": "2021-01-24",
       "title": "𝗚𝗿𝗲𝗮𝘁 𝗣𝗿𝗼𝗱𝘂𝗰𝘁!",
    "content": "Works precisely as advertised! I get sleepy within 30 minutes of taking my pill at night and it does seem to have a positive impact on helping to keep my weight down.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Bianca",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 11,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 19,
       "parent": null,
       "created": "2020-12-29",
       "modified": "2020-12-29",
       "title": "𝗞𝗲𝘆 𝘁𝗼 𝗳𝗮𝘁 𝗹𝗼𝘀𝘀 𝗮𝗻𝗱 𝗴𝗼𝗼𝗱 𝘀𝗹𝗲𝗲𝗽",
    "content": "Love this product for fat loss! I am really sensitive to the stimulants in a lot of fat burning pills, but this one is perfect! It’s awesome because over the span of just a month I have noticed a huge difference. It has also even improved my sleep at night thanks to the melatonin it contains. \n \n KaiserFit never fails to impress me!",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Courtney Hall",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 14,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 20,
       "parent": null,
       "created": "2020-11-17",
       "modified": "2020-11-17",
       "title": "𝗔𝗺𝗮𝘇𝗶𝗻𝗴",
    "content": "Takes off the weight & helps you sleep. LOVE THIS STUFF!!!!",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Kristina Peterson",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 21,
       "parent": null,
       "created": "2020-10-12",
       "modified": "2020-10-12",
       "title": "𝗻𝗶𝘁𝗲 𝗯𝘂𝗿𝗻",
    "content": "i've been using this product for a couple years now and i absolutely love it! sleep is essential to recovery. the melatonin helps me get a restful nights sleep and helps my body burn calories without stimulants.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Rose S",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 22,
       "parent": null,
       "created": "2020-08-08",
       "modified": "2020-08-08",
       "title": "𝗚𝗿𝗲𝗮𝘁 𝘀𝗹𝗲𝗲𝗽 𝗴𝗿𝗲𝗮𝘁 𝘄𝗲𝗶𝗴𝗵𝘁𝗹𝗼𝘀𝘀",
    "content": "This product has the perfect dose of melatonin to help me get a restful sleep with a day full of stimulants. I'm also down a few extra pounds with nothing else changed in my routine. Definitely recommend!",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Jesse",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 9,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 23,
       "parent": null,
       "created": "2020-07-25",
       "modified": "2020-07-25",
       "title": "𝗪𝗼𝗿𝗸𝗲𝗱 𝘄𝗲𝗹𝗹!",
       "content": "Will buy again, helped with cravings, sleep and actual saw noticeable fat loss.",
        "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Bonnie Dawson",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 24,
       "parent": null,
       "created": "2020-05-17",
       "modified": "2020-05-17",
       "title": "𝗻𝗼𝗻 𝘀𝘁𝗶𝗺𝘂𝗹𝗮𝘁𝗶𝗻𝗴",
    "content": "Love this product! I previously tried products similar to this one but found that most of them would contain stimulants and would prevent me from sleeping. this has helped me sleep with no problems and keeps my appetite controlled throughout the day.",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Clara Grey",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 25,
       "parent": null,
       "created": "2020-03-09",
       "modified": "2020-03-09",
       "title": "<strong>This product will save your life and help you reach the finish line!</strong>",
    "content": "I used to wake up in the middle of the night extremely hungry and craving something sweet and before I knew it, I would eat everything in sight and cancel out all the hard work I put in at the gym. This product not only helped me sleep deeply and relax more but even if I woke up to go to the bathroom, I didn't feel any cravings or hunger. I will continue buying this product for the rest of my life!!",
    "attachments": [],
       "pings": [],
      "page": 5,
       "creator": 1,
       "fullname": "Emily T",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 16,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 26,
       "parent": null,
       "created": "2020-02-24",
       "modified": "2020-02-24",
       "title": "𝗕𝘂𝗿𝗻 𝗳𝗮𝘁 𝗶𝗻 𝘆𝗼𝘂𝗿 𝘀𝗹𝗲𝗲𝗽",
    "content": "It helps me slim down after I’ve gone off the deep end on weekend and it gives me better sleep than if I don’t take the supplement. I also feel like I recover a little better on the days I take these lil guys",
      "attachments": [],
       "pings": [],
      "page": 5,
       "creator": 1,
       "fullname": "Alana P.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 27,
       "parent": null,
       "created": "2020-02-12",
       "modified": "2020-02-12",
       "title": "𝗦𝗹𝗲𝗲𝗽 !!!!",
    "content": "The hardest thing about working out at night is going to bed after, with QNB I easily fall asleep and burn fat while doing it. MUST HAVE",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Rachael",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    ]
    
    var usersArray = [
       {
          id: 1,
          fullname: "Current User",
          email: "current.user@viima.com",
          profile_picture_url: "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png"
       }
      
    ]
    