var commentsArray = [

    {
       "id": 1,
       "parent": null,
       "created": "2021-10-29",
       "modified": "2021-09-18",
       "title": " ... is something you mix up and feel your body love what you put into it",
         "content": "This is something you mix up and feel your body love what you put into it. Energy, mental focus and bust a feeling of your body feeling well. It literally takes about 20 minutes after you drink it. I mix mine with protein powder and just started adding Moringa as well. I'm good to go till I go to bed. I give it a 5 star because it is raw organic and full of veggies, fruits, grasses. It's a ton cheaper than buying organic fresh fruits and veggies and other things. I will use this for many many years to come.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Emelia",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 8,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 2,
       "parent": null,
       "created": "2021-10-04",
       "modified": "2021-10-01",
       "title": "PERFECT NUTRITION! All you need.",
    "content": "I use in shake 2 x daily. Im diabetic and have severe digestion issues. This product has lowered my sugar from 450 to 105. I no longer need insulin. So nutritious you could live on just the shakes! My body responds immediately with energy and bright mind.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Louise A.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 9,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 3,
       "parent": null,
       "created": "2021-08-30",
       "modified": "2021-09-21",
       "title": "Digestive qualities WILL relieve constipation.",
       "content": "I use this to raise my veggie consumption easily, what I didn’t realize is that is also VERY helpful for constipation relief. Works well and I usually have ALL my bloat gone by morning, produce a BM and feel lighter. My skin clears up when I use this consistently. I have much more natural energy and my digestion is better.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Eliza Ward",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 4,
       "parent": null,
       "created": "2021-07-09",
       "modified": "2021-08-19",
       "title": "Helped me lose 35 pounds of fat.",
      "content": "A very healthy alternative to eating breakfast burritos.",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Katie",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 5,
       "parent": null,
       "created": "2021-07-01",
       "modified": "2021-10-16",
       "title": "This is my favorite greens in the world",
    "content": "This is my favorite green in the world...! I have been taking this product for years and LOVE IT! Luckily, I can proudly say after trying this multiple times with different types of smoothies (water, coconut water, juices) that this is a great tasting mix. Plus, there are no added 'junk' ingredients your body doesn't need. I would highly recommend trying this product out in your next smoothie!",
       "attachments": [],
       "pings": [],
        "page": 1,
       "creator": 1,
       "fullname": "Teresa M",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 6,
       "parent": null,
       "created": "2021-06-28",
       "modified": "2021-10-09",
       "title": "I actually feel better when taking this product",
    "content": "I purchased another green juice powder about 2 weeks ago. I won't say the name, but it didn't list any vitamins on the label like this one does. I did some research and this product was in every list. I decided to buy it, and now I'm so happy with it, I'm writing this 5 star review. I can't be 100% sure, but I know I feel like I have more energy and just generally good/happy, and the only thing that's changed is me taking this product.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Shania",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 8,
       "parent": null,
       "created": "2021-05-31",
       "modified": "2021-09-28",
       "title": "Boosts my daily nutritional standing in no time",
    "content": "I've been using this powder for almost a decade. It is consistently good. I'm over 60, now, and work full time. I feel that the ability to ingest so much vegetable material every day without thinking about, or spending time prepping, it has been a central part of maintaining my health. I'm often too busy to do the meal prep, but never too busy to drink a small shake to make all my morning vitamins easier to swallow.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Phoebe",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 9,
       "parent": null,
       "created": "2021-05-17",
       "modified": "2021-09-17",
       "title": "Absolute best!!!",
      "content": "This stuff is fantastic. I ordered it because I absolutely hate veggies and needed a way to get more greens into my diet. I’ve tried several other brands and this one by far tastes the best!! No adverse side effects, no upset stomach. This has become part of my daily routine.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Yasmin Russell",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 10,
       "parent": null,
       "created": "2021-05-03",
       "modified": "2021-08-17",
       "title": "Greenie",
    "content": "Good stuff. I love it. I enjoy having this in the morning around 7am. I mix one scoop each morning in a glass of water (well, I use a jar and shake it vigorously to mix it) then drink it down. Very pleasant taste and a great effect on the body and mind. I love this because it has a lot of good ingredients in it. You will too. This makes me feel good.",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Lillie ",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 11,
       "parent": null,
       "created": "2021-04-25",
       "modified": "2021-08-24",
       "title": "Great tastes and makes me healthier.",
      "content": "I substitute this for greens in my smoothies. The best greens I have ever tried! I’m so picky about taste! I blend it with a banana, mixed frozen fruit, frozen avocado chunks, spinach and water and it’s the best smoothie!",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Betty Freeman",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 12,
       "parent": null,
       "created": "2021-04-18",
       "modified": "2021-06-13",
       "title": "This green drink powder is a game changer!",
    "content": "It's difficult to eat the suggested daily servings of vegetables. I started drinking this green drink to improve my nutritional intake. What a difference it's made to my well-being. 5 servings each week has reduced the inflammation I battled for years, no more sore knees and ankles. I have lots of energy and do not crave carbs. I eat a moderate amount of carbs and salad for at least one meal each day. The only habit I have changed is this green drink.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Crystal B.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 4,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 13,
       "parent": null,
       "created": "2021-03-20",
       "modified": "2021-06-01",
       "title": "Awesome awesome product",
    "content": "This product will be with me forever. I think this was my 10th or so purchase of this product. I stopped drinking protein shakes after the gym and switched to this. Great way to start the day and then I don't care if I eat any vegetables with my meals.",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Hannah",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 14,
       "parent": null,
       "created": "2021-03-17",
       "modified": "2021-05-26",
       "title": "My new favorite Green drink!!",
    "content": "First time buying this brand. Very easy to drink. I added to a cup of water and it tasted pretty good! Will definitely buy again!",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "April. V",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 15,
       "parent": null,
       "created": "2021-02-28",
       "modified": "2021-05-04",
       "title": "Look no further! 🏆",
    "content": "Happy to see this product is back in stock! I live an active lifestyle but always have a tough time waking up in the morning. Usually it takes multiple cups of coffee to function properly. I searched through many options & this brand made the cut. I've noticed a marked difference in my overall energy and digestion. I'm sure others do the same. The price is just another plus! I went to buy it again a few weeks ago & was sad to see it out of stock... I ended up purchasing a different brand that tastes like dirt & dead leaves. 😖 I'll be going back to this one & stocking up!",
       "attachments": [],
       "pings": [],
         "page": 3,
       "creator": 1,
       "fullname": "Zoe Howard",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 16,
       "parent": null,
       "created": "2021-02-09",
       "modified": "2020-04-21",
       "title": "Great vegie substitute",
    "content": "I have a very hard time getting vegetables down so decided I would try a 'green powder' made from vegetables and at least get some nutrients. Luckily I started with this brand which tastes fine, dissolves easily, and doesn't cause any internal discomfort. I'm subscribing now to get one container every month and may increase that as I go from once a day to twice a day. I mix it with non-fat milk, a banana, perhaps a peach or blueberries, yogurt, and chai seeds. The smoothie is REALLY filling, takes me a while to get the whole thing down. This product is just so easy, I really like it.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Gabriella",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 17,
       "parent": null,
       "created": "2021-02-01",
       "modified": "2021-03-20",
       "title": "Useful",
    "content": "I use this product nearly daily to help me get nutrition from vegetables. I've been using it for a couple years and plan to continue. I don't seem to be able to plan to keep the veggies on hand needed for a homemade shake so this is the next best thing.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Daisy J",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 18,
       "parent": null,
       "created": "2020-01-27",
       "modified": "2021-01-24",
       "title": "The best Green food supplement!",
    "content": "I have tried many green food supplement powders & by far this one is the best!! It dissolves quickly & the flavor is delicious. I have been a fan of KaiserFit for years now.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Maria Johnson",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 19,
       "parent": null,
       "created": "2020-12-14",
       "modified": "2020-12-29",
       "title": "Great in the morning before exercise",
    "content": "I was searching for something to consume prior to exercising in the morning, and this is perfect for me. It's not too heavy like some protein drinks or acidic like orange or V8 juice.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Natalie",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 20,
       "parent": null,
       "created": "2020-12-07",
       "modified": "2020-11-17",
       "title": "Love it!!",
    "content": "Hubbie and I make this our first 'meal' of the day. Hubbie and I both enjoy it a lot. The taste is 'green' but it's not gritty or grassy. We don't mind the flavor at all. The sweetness is just right. We're into organic eating so we like that this product is totally organic and not going to 'kill us' with toxic additives and GMO's.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Samantha",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 21,
       "parent": null,
       "created": "2020-10-20",
       "modified": "2020-10-12",
       "title": "Amazing Product!",
    "content": "I ordered this to ensure I get my daily veggies and fruits. It ended up benefiting me in so many more ways.. I have tons of energy and don't feel hungry.. The taste is also pretty good to!",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Martha Vargas",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 22,
       "parent": null,
       "created": "2020-08-23",
       "modified": "2020-08-08",
       "title": "Greens",
    "content": "Excellent product, nice boost to my smoothie in the morning. Has a variety of greens for excellent energy. Blends easily, tastes very good for greens.",
       "attachments": [],
       "pings": [],
        "page": 4,
       "creator": 1,
       "fullname": "Jasmin. J",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 23,
       "parent": null,
       "created": "2020-07-16",
       "modified": "2020-07-25",
       "title": "Greens, yes!",
       "content": "I am and have never been a dark green veggie eater. So, I haven't been getting the nutrients from greens as I should. I can eat Brocolli raw, carrots raw, cabbage raw, & many more. I love a good raw, fresh salad. But cooked leafy green veggies blech! I am aware of being healthy & eating right so I thought this might be a good thing to try. This product is awesome. It addresses so many physical issues. My digestion system has always been slow & this seems to speed it up.",
        "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Courtney Reed",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 24,
       "parent": null,
       "created": "2020-07-09",
       "modified": "2020-05-17",
       "title": "So excited I found this!",
    "content": "This is the type of product I have been looking for! I try to keep a healthy, balanced diet, but I have been looking for a superfood supplement to add to my daily protein shakes. This supplement powder has far exceeded my expectations. This product is loaded with greens and antioxidants, but also contains probiotics and digestive enzymes. Plus there's no sugar added! It dissolves easily into my shakes, gives me an energy boost and tastes great. I couldn't ask for anything more! This will now be a staple in my healthy lifestyle. So glad I stumbled onto this product!",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Leia",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 25,
       "parent": null,
       "created": "2020-06-26",
       "modified": "2020-03-09",
       "title": "Loved it",
    "content": "Great product",
    "attachments": [],
       "pings": [],
      "page": 5,
       "creator": 1,
       "fullname": "Paula",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },

    {
        "id": 26,
        "parent": null,
        "created": "2020-06-17",
        "modified": "2020-03-09",
        "title": "Go for it!",
     "content": "This stuff... I don’t know what it is, but I’m hooked. I definitely feel better and have more energy!",
     "attachments": [],
        "pings": [],
       "page": 5,
        "creator": 1,
        "fullname": "Catherine A",
        "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
        "created_by_admin": false,
        "created_by_current_user": false,
        "upvote_count": 0,
        "user_has_upvoted": false,
        "is_new": false
     },

     {
        "id": 27,
        "parent": null,
        "created": "2020-05-19",
        "modified": "2020-03-09",
        "title": "I was skeptical but not anymore",
     "content": "I was told by a nutritionist that I needed to improve my good bacteria in the stomach and after trying a couple of alternatives to this one I decided to stick with this one. I had 'stuff' in my intestine that probably was camping there for longer than I thought it was possible. Kaiser Greens shoe them away and kindly (for me). Valuable product.",
     "attachments": [],
        "pings": [],
       "page": 5,
        "creator": 1,
        "fullname": "Elsie Warren",
        "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
        "created_by_admin": false,
        "created_by_current_user": false,
        "upvote_count": 1,
        "user_has_upvoted": false,
        "is_new": false
     },

     {
        "id": 28,
        "parent": null,
        "created": "2020-05-02",
        "modified": "2020-03-09",
        "title": "My brain fog is gone.",
     "content": "I'm trying to eat healthier, so I thought I would try this for starters. Within a few days my brain fog has vanished. I'm no longer content sitting on the couch in front of the TV. I feel like I need to be doing something now. Where I didn't want to do @#$& before. I can't even stand watching tv now. Winter is here. WTH am I supposed to do with my time? Lol. I've started painting the rooms in my house.<br><br> This is no lie, and no joke. I read similar reviews. Don't take my word for it. Read a few yourself.",
     "attachments": [],
        "pings": [],
       "page": 5,
        "creator": 1,
        "fullname": "Chelsea",
        "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
        "created_by_admin": false,
        "created_by_current_user": false,
        "upvote_count": 4,
        "user_has_upvoted": false,
        "is_new": false
     },
    
  
    
    ]
    
    var usersArray = [
       {
          id: 1,
          fullname: "Current User",
          email: "current.user@viima.com",
          profile_picture_url: "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png"
       }
      
    ]
    